[project]
name = "mcbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "negineri", email = "negineri@sfc.wide.ad.jp" }]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
mcbot = "mcbot:main"

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"
